### ISSUE TITLE
job completion callbacks

### ISSUE THREAD

**Issue by jim-toth** [Nerfbotxyz/nerfbot-rest-api#35]
use a new redis queue `callbacks`
- [x] test uploads still work :smile:
- [ ] test the callback actually fires

**Comment by Mallinanga** [comment]
After each completed job, an http POST request should be made at a specified customizable endpoint.

The data of that request should be the same as if I did a GET on /nerf/jobs/:jobId
For example, after a train job is completed the post request back should look like this:

`
{
  "id": "78018b02-7d87-45b1-8bf6-30c714bbe6b6",
  "userId": 1,
  "apiKey": "XXX",
  "status": "COMPLETE",
  "jobName": "train",
  "jobData": {
    "trainingId": "834fd8f0-8a63-4415-8a00-cb9ec0ed0ad2",
    "processedId": "e272b8ab-800d-47b2-af43-e7572ce9d961"
  },
  "created_at": "2023-05-28T14:54:19.260Z",
  "updated_at": "2023-05-28T15:15:18.426Z"
}
`

Maybe not only on complete events, but on errors too. But that's of secondary importance.
