### ISSUE TITLE
request tracking with carryover label information

### ISSUE THREAD

**Issue by Nopfed** [Nerfbotxyz/nerfbot-rest-api#57]
To help better keep track of which requests are for which upload/training/render, etc. during testing, it would be beneficial to have some sort of human-readable label that carries across jobs to solve this.

**Comment by jim-toth** [comment]
hypothetically, this could be the filename from the form data on upload - we're actually just throwing this information out
however, we could potentially allow the user to explicitly choose a custom label (varchar 255 or something)

**Comment by jim-toth** [comment]
@Nopfed I can see this ideally working this way:

For each step (upload, process, train, render, export) allow the user to provide a custom `label` in the POST body.
If not provided for upload step, use the original upload's filename for the `label`.
If not provided for steps after upload, carry over the `label` from previous step.
Allow the user to override the `label` at each step.
