### ISSUE TITLE
Add Content-Length header to downloads

### ISSUE THREAD

**Issue by jim-toth** [Nerfbotxyz/nerfbot-rest-api#60]
- [ ] render downloads
  - See: https://github.com/Nerfbotxyz/nerfbot-rest-api/blob/master/src/interface/router/nerf/renders.ts#L83
- [ ] export downloads
  - See: https://github.com/Nerfbotxyz/nerfbot-rest-api/blob/master/src/interface/router/nerf/exports.ts#L80
  
Basically, just add `Content-Length` header with byte length of the download.  Might need to figure out how to do that as they are streams :)

**Comment by jim-toth** [comment]
@Nopfed try test lorge foile

**Comment by Nopfed** [comment]
downloads working. large file did not finish rendering.
